#include<iostream>
using namespace std;

int func(int n){
    int fac = 1;
    for(int i = 2;i<=n;i++){
        fac = fac*i;
    }
    int count = 0;
    while(true){
        int temp = fac%10;
        if(temp != 0){
            return count;
        }
        else{
            fac = fac/10;
            count++;
        }
    }
}


//in this solution . first factorial is calculated and then trailing zeros are calculated.
// time complexity - O(n)



int func(int n){
    int count = 0;
    for(int i=5;i<=n;i=i*5){
        count = count + n/i;
    }
    return count;
}

//in this , solution is generated by removing the 5's which are responsible.
// general formula : number of trailing zeros = n/5 + n/25 + n/125 + ....... + n/k where k < n



int main(){
    cout << func(100);
    return 0;
}